-- Add edit/delete metadata columns to chat_messages.
ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS edited TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS deleted TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL DEFAULT NULL;
